version: "3.7"

services:
  cadvisor:
    # image: gcr.io/cadvisor/cadvisor:v0.47.0
    image: gcr.io/cadvisor/cadvisor:v0.52.1
    restart: unless-stopped
    container_name: "cadvisor"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 42005:8080

