version: "3.7"

services:
  nginx:
    image: nginx:1.23.3
    restart: always
    container_name: "nginx"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d # no need to modify permissions
    ports:
      - 80:80
      - 443:443

  gitlab:
    image: gitlab/gitlab-ce:15.8.1-ce.0
    restart: always
    container_name: "gitlab"
    hostname: "gitlab.dea"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://192.168.1.45"
    ports:
      - 42001:80
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    shm_size: "256m"

  nexus:
    image: sonatype/nexus3:3.46.0
    restart: always
    container_name: "nexus3"
    volumes:
      - ./nexus/data:/nexus-data # ensure "chown -R 200:200 ./nexus/data"
    ports:
      - 42002:8081

  prometheus:
    image: prom/prometheus:v2.42.0
    container_name: "prometheus"
    ports:
      - 42003:9090
    volumes:
      - ./prometheus/data:/prometheus # ensure "chown -R 65534:65534 ./prometheus"
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml # ensure "chown -R 65534:65534 ./prometheus"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention=1d" 

  node-exporter:
    image: prom/node-exporter:v1.5.0
    user: root
    container_name: "node-exporter"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - 42004:9100
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: "cadvisor"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 42005:8080

  grafana:
    image: grafana/grafana:9.3.6
    container_name: "grafana"
    volumes:
      - ./grafana/data:/var/lib/grafana # ensure "chown -R 472:0 ./grafana/data"
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources # ensure "chown -R 472:0 ./grafana/provisioning"
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml # ensure "chown -R 472:0 ./grafana/dashboard.yaml"
      - ./grafana/dashboards:/var/lib/grafana/dashboards # ensure "chown -R 472:0 ./grafana/dashboards"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - DS_PROMETHEUS=Prometheus # this is Datasource name. See grafana/provisioning/datasources/prometheus.dea.yml
    depends_on:
      - prometheus
    ports:
      - 42006:3000
