version: "3.7"

services:
  nginx:
    image: nginx:1.23.3
    restart: always
    container_name: "nginx"
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d" # no need to modify permissions
    ports:
      - "80:80"
      - "443:443"

  gitlab:
    image: gitlab/gitlab-ce:15.8.1-ce.0
    restart: always
    container_name: "gitlab"
    hostname: "gitlab.dea"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://192.168.1.45"
    ports:
      - "42001:80"
    volumes:
      - "./gitlab/config:/etc/gitlab"
      - "./gitlab/logs:/var/log/gitlab"
      - "./gitlab/data:/var/opt/gitlab"
    shm_size: "256m"

  nexus:
    image: sonatype/nexus3:3.46.0
    restart: always
    container_name: "nexus3"
    volumes:
      - "./nexus/data:/nexus-data" # ensure "chown -R 200:200 /repos/infra/nexus/data"
    ports:
      - "42002:8081"
 
