version: "3.7"

services:
  jupyter:
    # image: jupyter/datascience-notebook:notebook-6.5.2
    image: quay.io/jupyter/datascience-notebook:2025-05-30
    restart: unless-stopped
    container_name: jupyter
    ports:
      - 42012:8888
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "password"
    volumes:
      - /storage/nvme/jupyter/notebooks:/home/jovyan/notebooks # ensure "chown -R 1000:100 ./jupyter"
