version: "3.7"
services:

  kafka:
    container_name: kafka
    image: bitnami/kafka:4.0.0
    restart: unless-stopped
    ports:
      - 42014:9092
      - 42015:9093
    volumes:
      - /storage/nvme/kafka:/bitnami/kafka # ensure "chown -R 1001:0 /storage/nvme/kafka"
    environment:
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.70:42014
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_NODE_ID: 1
      # KAFKA_BROKER_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@192.168.1.70:42015
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_KRAFT_CLUSTER_ID: L0ZEQh1yTbGhNNUE7-6wSQ

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.7.2
    restart: unless-stopped
    ports:
      - 42016:8080
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: 192.168.1.70:42014
      KAFKA_CLUSTERS_0_NAME: kafka-local-kraft
    depends_on:
      - kafka

