version: "3.7"

services:
  minio:
    # image: minio/minio:RELEASE.2023-02-27T18-10-45Z
    image: minio/minio:RELEASE.2025-05-24T17-08-30Z
    restart: unless-stopped
    container_name: minio
    ports:
      - 42010:9000
      - 42011:9001
    volumes:
      - /storage/ssd/minio:/data
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password"
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      MINIO_PROMETHEUS_JOB_ID: "minio" # same as in ./prometheus/prometheus.yml
      MINIO_PROMETHEUS_URL: "http://192.168.1.70:42003" # same as in ./prometheus/prometheus.yml
    command: server --console-address ":9001" /data
