{
 "title": "Nexus Repo Prometheus - cgroschupp",
 "description": "Nexus Dashboard for ocadotechnology/nexus-exporter",
 "tags": [ "nexus" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(nexus_events_total[5m])", "legendFormat": "{{level}}" }
   ]
  },
  {
   "title": "memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nexus_max_memory_bytes - nexus_free_memory_bytes",
     "legendFormat": "used"
    },
    { "expr": "nexus_max_memory_bytes", "legendFormat": "max" }
   ]
  },
  {
   "title": "read only state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "readonly_enabled" },
    { "expr": "readonly_freezeTime" },
    { "expr": "readonly_pending" }
   ]
  },
  {
   "title": "jetty thread pool total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"org_eclipse_jetty_util_thread_QueuedThreadPool.*_utilization\"}"
    },
    {
     "expr": "{__name__=~\"org_eclipse_jetty_util_thread_QueuedThreadPool.*_size\"}"
    }
   ]
  },
  {
   "title": "jvm thread states total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"jvm_thread_states_.*_count\"}"
    }
   ]
  },
  {
   "title": "threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_thread_states_count", "legendFormat": "threads states count" }
   ]
  },
  {
   "title": "http responses total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"org_eclipse_jetty_webapp_WebAppContext_.xx_responses_total\"}"
    }
   ]
  },
  {
   "title": "http requests total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"org_eclipse_jetty_webapp_WebAppContext_.*_requests_count\"}"
    }
   ]
  },
  {
   "title": "http responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(org_eclipse_jetty_webapp_WebAppContext_1xx_responses_total[5m])",
     "legendFormat": "1xx"
    },
    {
     "expr": "increase(org_eclipse_jetty_webapp_WebAppContext_2xx_responses_total[5m])",
     "legendFormat": "2xx"
    },
    {
     "expr": "increase(org_eclipse_jetty_webapp_WebAppContext_3xx_responses_total[5m])",
     "legendFormat": "3xx"
    },
    {
     "expr": "increase(org_eclipse_jetty_webapp_WebAppContext_4xx_responses_total[5m])",
     "legendFormat": "4xx"
    },
    {
     "expr": "increase(org_eclipse_jetty_webapp_WebAppContext_5xx_responses_total[5m])",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "http requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(org_eclipse_jetty_webapp_WebAppContext_trace_requests_count[5m])",
     "legendFormat": "trace"
    },
    {
     "expr": "increase(org_eclipse_jetty_webapp_WebAppContext_put_requests_count[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "increase(org_eclipse_jetty_webapp_WebAppContext_post_requests_count[5m])",
     "legendFormat": "post"
    },
    {
     "expr": "increase(org_eclipse_jetty_webapp_WebAppContext_other_requests_count[5m])",
     "legendFormat": "other"
    },
    {
     "expr": "increase(org_eclipse_jetty_webapp_WebAppContext_options_requests_count[5m])",
     "legendFormat": "options"
    },
    {
     "expr": "increase(org_eclipse_jetty_webapp_WebAppContext_move_requests_count[5m])",
     "legendFormat": "move"
    },
    {
     "expr": "increase(org_eclipse_jetty_webapp_WebAppContext_head_requests_count[5m])",
     "legendFormat": "head"
    },
    {
     "expr": "increase(org_eclipse_jetty_webapp_WebAppContext_get_requests_count[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "increase(org_eclipse_jetty_webapp_WebAppContext_delete_requests_count[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "increase(org_eclipse_jetty_webapp_WebAppContext_connect_requests_count[5m])",
     "legendFormat": "connect"
    }
   ]
  },
  {
   "title": "Active Web requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "org_eclipse_jetty_webapp_WebAppContext_active_dispatches"
    },
    {
     "expr": "org_eclipse_jetty_webapp_WebAppContext_active_requests"
    },
    {
     "expr": "org_eclipse_jetty_webapp_WebAppContext_active_suspended"
    }
   ]
  },
  {
   "title": "jvm memory total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "jvm_memory_total_max" },
    { "expr": "jvm_memory_total_used" }
   ]
  },
  {
   "title": "jvm memory heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "jvm_memory_heap_max" },
    { "expr": "jvm_memory_heap_used" }
   ]
  },
  {
   "title": "jvm memory non-heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "jvm_memory_non_heap_max" },
    { "expr": "jvm_memory_non_heap_used" }
   ]
  },
  {
   "title": "File Blob  Store",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "org_sonatype_nexus_blobstore_file_FileBlobStore_delete_timer_count",
     "legendFormat": "blob - delete"
    },
    {
     "expr": "org_sonatype_nexus_blobstore_file_FileBlobStore_create_timer_count",
     "legendFormat": "blob - create"
    },
    {
     "expr": "org_sonatype_nexus_blobstore_file_FileBlobStore_get_timer_count",
     "legendFormat": "blob - get"
    },
    {
     "expr": "org_sonatype_nexus_blobstore_file_FileBlobStore_copy_timer_count",
     "legendFormat": "blob - copy"
    }
   ]
  },
  {
   "title": "jvm memory pools used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"jvm_memory_pools_.*used\"}"
    }
   ]
  },
  {
   "title": "nexus ui totals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"com_sonatype_nexus_.*_ui_.*_total\"}"
    }
   ]
  }
 ]
}